/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/Room.glb 
*/
"use client";
import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import MaterialDecal from "./MaterialDecal";

export default function Room(props) {
  const { nodes } = useGLTF("./Models/Room.glb");
  const { ROOM, TECH, PLANT, Scene, ...rest } = nodes;

  const [
    textureRoom,
    texturePlant,
    texturePlanes,
    profilePhotoWallpaperTexture,
    SkillsLeftWallpaperTexture,
    SkillsRightWallpaperTexture,
    TvWallpaperTexture,
    PaintingWallpaperTexture_01,
    PaintingWallpaperTexture_02,
    PaintingWallpaperTexture_03,
    PaintingWallpaperTexture_04,
    profilePhotoTexture,
    SkillsLeftTexture,
    SkillsRightTexture,
    PaintingTexture_01,
    PaintingTexture_02,
    PaintingTexture_04
  ] = useTexture(
    [
      "./Textures/ROOM.jpg",
      "./Textures/PLANTS.jpg",
      "./Textures/PLANES.jpg",
      "./Textures/wallpapers/pl.jpg",
      "./Textures/wallpapers/Computer_Left.jpg",
      "./Textures/wallpapers/Computer_Right.jpg",
      "./Textures/wallpapers/TV.jpg",
      "./Textures/wallpapers/pr01.jpg",
      "./Textures/wallpapers/pr02.jpg",
      "./Textures/wallpapers/pr03.jpg",
      "./Textures/wallpapers/pr04.jpg",
      "./Textures/sections/about.jpg",
      "./Textures/sections/cl.jpg",
      "./Textures/sections/cr.jpg",
      "./Textures/sections/pr01.jpg",
      "./Textures/sections/pr02.jpg",
      "./Textures/sections/pr04.jpg"
    ],
    (textures) => {
      textures.map((texture) => {
        texture.flipY = false;
      });
    }
  );

  // const scroll = useScroll();
  // useFrame(() => {
  //   console.log("Offset", scroll.offset);
  // });

  return (
    <>
      <group>
        <mesh
          geometry={ROOM.geometry}
          position={ROOM.position}
          scale={ROOM.scale}
          rotation={ROOM.rotation}
        >
          <meshBasicMaterial map={textureRoom} />
        </mesh>
        <mesh
          geometry={TECH.geometry}
          position={TECH.position}
          scale={TECH.scale}
          rotation={TECH.rotation}
        >
          <meshBasicMaterial map={texturePlanes} />
        </mesh>
        <mesh
          geometry={PLANT.geometry}
          position={PLANT.position}
          scale={PLANT.scale}
          rotation={PLANT.rotation}
        >
          <meshBasicMaterial map={texturePlant} />
        </mesh>
        <mesh
          geometry={rest["Computer_Left"].geometry}
          position={rest["Computer_Left"].position}
          scale={rest["Computer_Left"].scale}
          rotation={rest["Computer_Left"].rotation}
        >
          <MaterialDecal
            position={[0, 0, 0]}
            rotation={[1, 0, 0]}
            scale={[2, 2, 2]}
            map={SkillsLeftWallpaperTexture}
            updateMap={SkillsLeftTexture}
            range={[0.351, 0.432]}
          />
        </mesh>
        <mesh
          geometry={rest["Computer_Right"].geometry}
          position={rest["Computer_Right"].position}
          scale={rest["Computer_Right"].scale}
          rotation={rest["Computer_Right"].rotation}
        >
          <MaterialDecal
            position={[0, 0, 0]}
            rotation={[1, 0, 0]}
            scale={[2, 2, 2]}
            map={SkillsRightWallpaperTexture}
            updateMap={SkillsRightTexture}
            range={[0.351, 0.432]}
          />
        </mesh>
        <mesh
          geometry={rest["PaintingL"].geometry}
          position={rest["PaintingL"].position}
          scale={rest["PaintingL"].scale}
          rotation={rest["PaintingL"].rotation}
        >
          <MaterialDecal
            position={[0, 0, 0]}
            rotation={[1, 0, 0]}
            scale={[2, 1.8, 2]}
            map={profilePhotoWallpaperTexture}
            updateMap={profilePhotoTexture}
            range={[0.1405, 0.196]}
          />
        </mesh>
        <mesh
          geometry={rest["PaintingR01"].geometry}
          position={rest["PaintingR01"].position}
          scale={rest["PaintingR01"].scale}
          rotation={rest["PaintingR01"].rotation}
        >
          <MaterialDecal
            position={[0, 0, 0]}
            rotation={[2, 0, 0]}
            scale={[2, 2, 2]}
            map={PaintingWallpaperTexture_01}
            updateMap={PaintingTexture_01}
            range={[0.64, 0.69]}
          />
        </mesh>
        <mesh
          geometry={rest["PaintingR02"].geometry}
          position={rest["PaintingR02"].position}
          scale={rest["PaintingR02"].scale}
          rotation={rest["PaintingR02"].rotation}
        >
          <MaterialDecal
            position={[0, 0, 0]}
            rotation={[2, 0, 0]}
            scale={[2, 2, 1]}
            map={PaintingWallpaperTexture_02}
            updateMap={PaintingTexture_02}
            range={[0.64, 0.69]}
          />
        </mesh>
        <mesh
          geometry={rest["PaintingR03"].geometry}
          position={rest["PaintingR03"].position}
          scale={rest["PaintingR03"].scale}
          rotation={rest["PaintingR03"].rotation}
        >
          <MaterialDecal
            position={[0, 0, 0]}
            rotation={[1, 0, 0]}
            scale={[2, 2, 2]}
            map={PaintingWallpaperTexture_03}
          />
        </mesh>
        <mesh
          geometry={rest["PaintingR04"].geometry}
          position={rest["PaintingR04"].position}
          scale={rest["PaintingR04"].scale}
          rotation={rest["PaintingR04"].rotation}
        >
          <MaterialDecal
            position={[0, 0, 0]}
            rotation={[1, 0, 0]}
            scale={[2, 2, 2]}
            map={PaintingWallpaperTexture_04}
            updateMap={PaintingTexture_04}
            range={[0.64, 0.69]}
          />
        </mesh>
        <mesh
          geometry={rest["WallTv"].geometry}
          position={rest["WallTv"].position}
          scale={rest["WallTv"].scale}
          rotation={rest["WallTv"].rotation}
        >
          <MaterialDecal
            position={[0, 0, 0]}
            rotation={[1, 0, 0]}
            scale={[2, 2, 2]}
            map={TvWallpaperTexture}
          />
        </mesh>
      </group>
    </>
  );
}

useGLTF.preload("./Models/Room.glb");
